ALTER TABLE users ADD COLUMN cover_image VARCHAR(255);
ALTER TABLE users ADD COLUMN location VARCHAR(100);
ALTER TABLE users ADD COLUMN auto_reply_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN auto_reply_text VARCHAR(500);
ALTER TABLE users ADD COLUMN vacation_mode BOOLEAN DEFAULT FALSE;
